name: Endor Labs Scan
on:
  workflow_dispatch:
    inputs:
      api:
        description: "Enter the target Endor Labs API"
        required: true
        type: choice
        default: https://api.endorlabs.com
        options:
        - https://api.staging.endorlabs.com
        - https://api.endorlabs.com
      tenant_name:
        description: "Enter your Endor Labs namespace"
        required: true
        type: string
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      security-events: write
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: Endor Labs Scan
          uses: endorlabs/github-action@v1.1.4
          with:
            namespace: ${{ github.event.inputs.tenant_name }}
            scan_summary_output_type: 'table'
            scan_dependencies: true
            scan_secrets: true
            scan_git_logs: true
            pr: false
            sarif_file: 'findings.sarif'
            additional_args: "--as-default-branch --api=${{ github.event.inputs.api }}"

        - name: Upload findings to GitHub
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'findings.sarif'
