name: Endor Labs Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  endor-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Endorctl
      - name: Set up Endorctl
        run: |
          curl -sSL https://cli.endorlabs.com/install.sh | sh
          export PATH=$PATH:/home/runner/.endorctl

      # Step 3: Authenticate with Endorctl
      - name: Authenticate with Endorctl
        env:
          ENDOR_API_KEY: ${{ secrets.ENDOR_API_KEY }}
        run: |
          endorctl init --api-key $ENDOR_API_KEY

      # Step 4: Run Endor Labs Scan
      - name: Run Endor Labs Scan
        run: |
          endorctl scan --namespace "jinlee" --project "brownie"

      # Step 5: Upload Scan Results (optional)
      - name: Upload Endorctl Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: endorctl-report
          path: endorctl-report.json
